CREATE TABLE TEAM (
    TEAM_ID INT PRIMARY KEY,
    TEAM_NAME VARCHAR(100) NOT NULL,
    SALARY_CAP DECIMAL(15,2) NOT NULL,
    SALARY_FLOOR DECIMAL(15,2) NOT NULL
);

CREATE TABLE PLAYER (
    PLAYER_ID VARCHAR(11) PRIMARY KEY,  --SSN OR RANDOM
    NAME VARCHAR(100) NOT NULL,
    POSITION VARCHAR(50) NOT NULL,
    POSITION_CATEGORY VARCHAR(50) NOT NULL
);

CREATE TABLE PLAYS_FOR (
    PLAYER_ID VARCHAR(11) NOT NULL,
    TEAM_ID INT NOT NULL,
    YEARS_PLAYED INT NOT NULL CHECK (YEARS_PLAYED > 0),
    PRIMARY KEY (PLAYER_ID, TEAM_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES PlAYER(PLAYER_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

CREATE TABLE CONTRACT (
    CONTRACT_ID INT PRIMARY KEY,
    PLAYER_ID VARCHAR(11) NOT NULL,
    TOTAL_SALARY DECIMAL(12,2) NOT NULL CHECK (TOTAL_SALARY > 0),
    YEARS_REMAINING INT NOT NULL CHECK (YEARS_REMAINING > 0),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID)
);

    
    
    
